### ISSUE TITLE
Add support for custom RGB colors

### ISSUE THREAD

**Issue by tboeckel** [amiga-mui/texteditor#1]
MUI's text enginge supports direct RGB colors for text via the \033P[RRGGBB] sequence. If possible TextEditor.mcc should be able to do the same as well, provided the system is able to handle direct RGB colors.

**Comment by afalkenhahn** [comment]
It would also be great if TextEditor.mcc could return direct RGB colours in its exported texts instead of pen references. In order to keep compatibility with older versions, a new tag could be introduced to enable this behaviour. If it is enabled, colour changes inside the text should be exported as \033P[RRGGBB] tokens instead of pen references. This would also increase consistency to other MUI classes like Floattext.mcc which also treat colours like that.

**Comment by tboeckel** [comment]
This feature will be implemented in V15.47.
