### ISSUE TITLE
Keybinding bug

### ISSUE THREAD

**Issue by ElenaXX** [amiga-mui/texteditor#19]
Version 15.47, MorphOS 3.9
Apparently I can't associate the combination rshift+up to Top and rshift+bottom to Bottom, also
I can't associate rshift+left to line start and rshift+right to line end. If I do, I always get text selection as
a result or other unpredictable text selection + movement.
Also (perhaps this is highly related to the wrong behaviour said above) the Block Qualifier doesn't accept
the "(mouse only)" option, I can change it but everytime I switch between pages I read "Shift" again.
Please fix it, thanks.

**Comment by tboeckel** [comment]
I just tried to reproduce this on AmigaOS3, but for me the snoop function works as expected. All combinations of the SHIFT key plus any cursor movement produce the the desired shortcut string if the "Snoop" button has been pressed before. Without the Snoop button one of course has to enter the shortcut string manually. Unfortunately you didn't state how exactly you try to set up the shortcut.

Regarding the block qualifier I just noticed that the attribute to set the current cycle entry was wrong (MUIA_Pendisplay_Spec instead of MUIA_Cycle_Active). This was definitely wrong.

**Comment by tboeckel** [comment]
Please try these rebuilt versions of TextEditor.mcc and TextEditor.mcp.
[texteditor_mos.zip](https://github.com/amiga-mui/texteditor/files/695519/texteditor_mos.zip)

**Comment by ElenaXX** [comment]
Dear Thore,
I'm glad to let u know that in the new version u just sent me the bug is gone :)

I was using the snoop button to enter the needed event. But I'm almost sure the
block qualifier bug was the indirect culprit. It's ok now.

Thank u very much for ur prompt and kind feedback,
best regards
 Elena


Hello Thore

On  9-Jan-2017, Thore Böckelmann wrote:
> Please try these rebuilt versions of TextEditor.mcc and TextEditor.mcp.
> [texteditor_mos.zip](https://github.com/amiga-mui/texteditor/files/695519/texteditor_mos.zip)
>
>
Regards
